name=SerialCommands
version=2.2.0
sentence=An Arduino library to tokenize and parse commands received over a serial port.
paragraph=Simple, small footprint, no dynamic memory allocation
category=Data Processing
architectures=*
